version: "3.8"
services:
  vecator:
    build: .
    image: catxpapa/vecator:latest
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    restart: always